import { TerrainType } from '@/types/tile';
export default {
  width: 240,
  height: 160,
  scale: 4,
  offset_x: 0,
  offset_y: 0,
  tiles: [
    [
      TerrainType.Mountain,
      TerrainType.Mountain,
      TerrainType.Architecture,
      TerrainType.Architecture,
      TerrainType.Architecture,
      TerrainType.Plain,
      TerrainType.Plain,
      TerrainType.Forest,
      TerrainType.Plain,
      TerrainType.Mountain,
      TerrainType.Mountain,
      TerrainType.Cliff,
      TerrainType.Cliff,
      TerrainType.Cliff,
      TerrainType.Cliff,
    ],
    [
      TerrainType.Plain,
      TerrainType.Plain,
      TerrainType.Plain,
      TerrainType.Architecture,
      TerrainType.Architecture,
      TerrainType.Plain,
      TerrainType.Plain,
      TerrainType.Forest,
      TerrainType.Plain,
      TerrainType.Mountain,
      TerrainType.Mountain,
      TerrainType.Cliff,
      TerrainType.Cliff,
      TerrainType.Cliff,
      TerrainType.Cliff,
    ],
  ],
};
